install.packages("IRkernel")
IRkernel::installspec(user = FALSE)
install.packages("RcolorBrewer")
install.packages("tidyverse")
install.packages("readxl")
install.packages("rvest")
install.packages("dplyr")
install.packages("tidyr")
install.packages("igraph")
install.packages("visNetwork")
install.packages("readr")
install.packages("ggplot2")
install.packages("ggraph")
install.packages("graphTweets")
install.packages("writexl")
install.packages("httr")
install.packages("proxy")
