install.packages(c("readr","igraph", "devtools","tidyr", "ggplot2", "dplyr","readxl", "rJava", "rcdk"))
library(devtools)
library(igraph)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(readxl)
library(rjava)
library(rcdk)
