---
title: "IQ_Script"
author: "Douglas Venegas"  
affiliations:
  - "CENIBiot-CENAT"
date: "2024-10-28"
output: 
  html_document:
    toc: true           
    toc_depth: 3        
    toc_float: true      
    theme: cerulean      
    highlight: tango     
    code_folding: hide  
    number_sections: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,       
  message = FALSE,   
  warning = FALSE,   
  fig.width = 7,     
  fig.height = 5,    
  fig.align = 'center',
  cache = TRUE      
)
knitr::opts_chunk$set(echo = TRUE)
```


Run the script to line 910 for an index based on your annotation library or run the script to line 64 and jump to line 910 for IQ based on NPAtlas annotations.

# Packages instalation

Load or install pacman to streamline package management

```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load("RColorBrewer", "tidyverse", "readxl", "rvest", "dplyr", "tidyr", "igraph", "visNetwork", 
               "readr", "ggplot2", "ggraph", "graphTweets", "writexl", "rJava", "rcdk", "proxy", "httr")
# Set JAVA_HOME environment variable for rJava
Sys.setenv(JAVA_HOME = 'C:/Program Files/Java/jdk-17')

```

# Inputs

Load network from a .graphML file. Change the file name as necessary
```{r}
graphml <- read_graph("Data/network_Crusemann.graphml", format = "graphml")
Metadata <- read_delim("Data/Metadata_Cruseman.csv", 
                       delim = ";", escape_double = FALSE, trim_ws = TRUE)

```

# List of directories to create

```{r}
Dirs <- c("Data/CSV_IQ", "Data/IQ_Plot","Data/CSV_IQNPA", "Data/IQNPA_Plot")
for (dir in Dirs) {
  if (!dir.exists(dir)) {
    dir.create(dir, recursive = TRUE)
  }
}
```

